version: '3.7'
services:
  mariadb:
    image: mariadb:10.9
    container_name: crazy_tower_mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - crazyTowerMariadb:/var/lib/mysql
volumes:
  crazyTowerMariadb:
